# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: imaotai-action

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '20 0,1 * * *'

env:
  TZ: Asia/Shanghai

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    #    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #          pip install pycryptodome requests beautifulsoup4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: start run
        env:
          PUSHPLUS_KEY: ${{ secrets.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 }}
          PRIVATE_AES_KEY: ${{ secrets.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 }}
        run: |
          python main.py

#        pip install flake8 pytest
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics